Modified Jenkins file again

diff --git a/.github/workflows/CI-CD Pipeline.yml b/.github/workflows/CI-CD Pipeline.yml
--- a/.github/workflows/CI-CD Pipeline.yml
+++ b/.github/workflows/CI-CD Pipeline.yml
@@ -52,21 +52,21 @@ jobs:
       - name: Sonar Qube Scan
         run: ./gradlew sonar
 
-#     - name: Check SonarQube Quality Gate
-#       env:
-#       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#       run: |
-#          STATUS=$(curl -s -u "${SONAR_TOKEN}:" \
-#            "https://sonar.your-server.com/api/qualitygates/project_status?projectKey=your_project_key" \
-#            | jq -r '.projectStatus.status')
-#
-#          # Check if Quality Gate status is "FAILED"
-#          if [ "$STATUS" == "FAILED" ]; then
-#            echo "Quality Gate FAILED. Stopping pipeline."
-#            exit 1
-#          else
-#            echo "Quality Gate PASSED."
-#          fi
+      - name: Check SonarQube Quality Gate
+        env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          STATUS=$(curl -s -u "${SONAR_TOKEN}:" \
+            "http://197.140.142.82:9000/api/qualitygates/project_status?projectKey=com.example:TP7" \
+            | jq -r '.projectStatus.status')
+
+          # Check if Quality Gate status is "FAILED"
+          if [ "$STATUS" == "FAILED" ]; then
+            echo "Quality Gate FAILED. Stopping pipeline."
+            exit 1
+          else
+            echo "Quality Gate PASSED."
+          fi
 
       - name: Build
         run: |
